spring:
  application:
    name: adocao-pets-api
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/adocao}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
springdoc:
  override-with-generic-response: false